# Generated by Django 6.0.3 on 2026-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='notes',
            new_name='brief_history',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='walkin_contact',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='walkin_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='walkin_first_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='walkin_last_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='walkin_middle_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='walkin_philhealth',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='walkin_sex',
        ),
        migrations.AddField(
            model_name='referral',
            name='bp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='designation',
            field=models.CharField(default='Sariaya Municipal Health Center', max_length=100),
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_file_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='referral',
            name='impression',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='pr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='rr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='services_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='temp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='walkin_age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='walkin_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='referral',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
