BARANGAYS = [
    ('Poblacion 1', 'Poblacion 1'),
    ('Poblacion 2', 'Poblacion 2'),
    ('Poblacion 3', 'Poblacion 3'),
    ('Poblacion 4', 'Poblacion 4'),
    ('Poblacion 5', 'Poblacion 5'),
    ('Poblacion 6', 'Poblacion 6'),
    ('Antipolo', 'Antipolo'),
    ('Balubal', 'Balubal'),
    ('Bignay 1', 'Bignay 1'),
    ('Bignay 2', 'Bignay 2'),
    ('Bucal', 'Bucal'),
    ('Canda', 'Canda'),
    ('Castañas', 'Castañas'),
    ('Concepcion 1', 'Concepcion 1'),
    ('Concepcion Banahaw', 'Concepcion Banahaw'),
    ('Concepcion Palasan', 'Concepcion Palasan'),
    ('Concepcion Pinagbukuran', 'Concepcion Pinagbukuran'),
    ('Gibanga', 'Gibanga'),
    ('Guisguis San Roque', 'Guisguis San Roque'),
    ('Guisguis Talon', 'Guisguis Talon'),
    ('Janagdong 1', 'Janagdong 1'),
    ('Janagdong 2', 'Janagdong 2'),
    ('Limbon', 'Limbon'),
    ('Lutucan 1', 'Lutucan 1'),
    ('Lutucan Bata', 'Lutucan Bata'),
    ('Lutucan Malabag', 'Lutucan Malabag'),
    ('Mamala 1', 'Mamala 1'),
    ('Mamala 2', 'Mamala 2'),
    ('Manggalang 1', 'Manggalang 1'),
    ('Manggalang Bantilan', 'Manggalang Bantilan'),
    ('Manggalang Kiling', 'Manggalang Kiling'),
    ('Manggalang Tulo-Tulo', 'Manggalang Tulo-Tulo'),
    ('Montecillo', 'Montecillo'),
    ('Morong', 'Morong'),
    ('Pili', 'Pili'),
    ('Sampaloc 1', 'Sampaloc 1'),
    ('Sampaloc 2', 'Sampaloc 2'),
    ('Sampaloc Bogon', 'Sampaloc Bogon'),
    ('Sto. Cristo', 'Sto. Cristo'),
    ('Talaan Aplaya', 'Talaan Aplaya'),
    ('Talaan Pantoc', 'Talaan Pantoc'),
    ('Tumbaga 1', 'Tumbaga 1'),
    ('Tumbaga 2', 'Tumbaga 2'),
]