# Generated by Django 6.0.3 on 2026-04-10 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('print', 'Print'), ('export', 'Export')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('record_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('barangay', models.CharField(blank=True, choices=[('Poblacion 1', 'Poblacion 1'), ('Poblacion 2', 'Poblacion 2'), ('Poblacion 3', 'Poblacion 3'), ('Poblacion 4', 'Poblacion 4'), ('Poblacion 5', 'Poblacion 5'), ('Poblacion 6', 'Poblacion 6'), ('Antipolo', 'Antipolo'), ('Balubal', 'Balubal'), ('Bignay 1', 'Bignay 1'), ('Bignay 2', 'Bignay 2'), ('Bucal', 'Bucal'), ('Canda', 'Canda'), ('Castañas', 'Castañas'), ('Concepcion 1', 'Concepcion 1'), ('Concepcion Banahaw', 'Concepcion Banahaw'), ('Concepcion Palasan', 'Concepcion Palasan'), ('Concepcion Pinagbukuran', 'Concepcion Pinagbukuran'), ('Gibanga', 'Gibanga'), ('Guisguis San Roque', 'Guisguis San Roque'), ('Guisguis Talon', 'Guisguis Talon'), ('Janagdong 1', 'Janagdong 1'), ('Janagdong 2', 'Janagdong 2'), ('Limbon', 'Limbon'), ('Lutucan 1', 'Lutucan 1'), ('Lutucan Bata', 'Lutucan Bata'), ('Lutucan Malabag', 'Lutucan Malabag'), ('Mamala 1', 'Mamala 1'), ('Mamala 2', 'Mamala 2'), ('Manggalang 1', 'Manggalang 1'), ('Manggalang Bantilan', 'Manggalang Bantilan'), ('Manggalang Kiling', 'Manggalang Kiling'), ('Manggalang Tulo-Tulo', 'Manggalang Tulo-Tulo'), ('Montecillo', 'Montecillo'), ('Morong', 'Morong'), ('Pili', 'Pili'), ('Sampaloc 1', 'Sampaloc 1'), ('Sampaloc 2', 'Sampaloc 2'), ('Sampaloc Bogon', 'Sampaloc Bogon'), ('Sto. Cristo', 'Sto. Cristo'), ('Talaan Aplaya', 'Talaan Aplaya'), ('Talaan Pantoc', 'Talaan Pantoc'), ('Tumbaga 1', 'Tumbaga 1'), ('Tumbaga 2', 'Tumbaga 2')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
