# Generated by Django 6.0.3 on 2026-04-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='Municipal Health Center, Poblacion, Sariaya, Quezon 4322')),
                ('office_phone', models.CharField(default='(042) 137-5XXX', max_length=50)),
                ('emergency_hotline', models.CharField(default='(042) 375-XXXX', max_length=50)),
                ('email', models.EmailField(default='mhcsariaya@quezon.gov.ph', max_length=254)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('vision', models.TextField(default='A united, peaceful and progressive municipality...')),
                ('mission', models.TextField(default='Inspired by and committed to delivering high quality...')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('hours', models.CharField(default='8:00 AM – 5:00 PM', max_length=50)),
                ('is_open', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g., Heart, Scale)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g., Stethoscope)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
