# Generated by Django 6.0.3 on 2026-04-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clinicinfo_clinicschedule_corevalue_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='before_visit',
            field=models.TextField(default='Bring a valid government-issued ID\nBring your PhilHealth card if applicable\nBring previous medical records if available\nArrive early to your appointment schedule\nWear a face mask and observe health protocols'),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='emergency_hotline',
            field=models.CharField(default='(+63) 912-345-6789', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='facebook_link',
            field=models.URLField(blank=True, default='https://facebook.com/MHC', null=True),
        ),
    ]
