# Generated by Django 6.0.3 on 2026-05-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clinicinfo_before_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('print', 'Print'), ('export', 'Export'), ('qr_scan', 'QR Scan'), ('restore', 'Restore')], max_length=20),
        ),
    ]
